pool:
  vmImage: windows-2019
variables:
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
jobs:
  - job: CI
    displayName: 'Build and Test'
    steps:
      - script: '.\build.cmd CI'
        displayName: Call Nuke CI Target
        env:
          NugetApiKey: $(NugetApiKey)
          DockerPassword: $(DockerPassword)

