FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR src
COPY NMica.sln .
COPY NMicaRunner/NMicaRunner.csproj NMicaRunner/NMicaRunner.csproj
COPY Docker/Docker.csproj Docker/Docker.csproj
COPY Common/Common.csproj Common/Common.csproj
COPY ../build/_build.csproj ../build/_build.csproj
RUN dotnet restore
COPY . .
RUN dotnet msbuild /p:RestorePackages=false /t:PublishLayer /p:PublishDir=/layer/ /p:DockerLayer=All NMicaRunner/NMicaRunner.csproj
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build /layer/package ./
COPY --from=build /layer/earlypackage ./
COPY --from=build /layer/project ./
COPY --from=build /layer/app ./
ENTRYPOINT ["dotnet", "NMicaRunner.dll"]
